name: Push/Pull on any branch

on: 
  push:
    branches-ignore: 
      - master
      - development  
  pull_request:
    branches-ignore: 
      - master
      - development

jobs:
  build:
    name: Setup & Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    
    - name: Install npm dependences, test-coverage
      run: |
        npm ci
        make test-coverage
      
    - name: Run ESLint checks
      run: npm run eslint
      
    - name: Run Unit tests
      run: npm run test
      
    - name: Run Coveralls
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.github_token }}

    - name: Run coverage
    - uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
