name: Push/Pull on master branch

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Setup & Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
#    - name: Start MongoDB As Docker
#      uses: wbari/start-mongoDB@v0.2
    - name: Install npm packages
      run: npm ci
    - name: ESLint checks
      run: npm run eslint
    - name: Run tests
      run: npm run test
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      
  deploy:
    name: Deploy to Docker
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
