name: Push/Pull on any branch

on: 
  push:
    branches:
      - '!master'
      - '!development'
  pull_request:
    branches:
      - '!master'
      - '!development'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: Install npm packages
      run: npm ci
    - name: ESLint checks
      run: npm run eslint
    - name: Run tests
      run: npm run test
