name: Push on any branch

on:
  push:
    branches-ignore:
      - master
      - development

jobs:
  setup:
    name: Setup & Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'

    - name: Install npm dependences
      run: npm install

    - name: ESLint test
      run: npm run eslint

    - name: Unit tests
      run: npm run test
