name: Push on master

on:
  push:
    branches:
      - master

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    env:
      JWT_ACCESS_SECRET: access
      JWT_REFRESH_SECRET: refresh

    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'

    - name: Install npm dependences
      run: npm install

    - name: ESLint test
      run: npm run eslint

    - name: Unit tests
      run: npm run test

    - name: Create coverage report
      run: npm run coverage

    - name: Upload to coveralls.io
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build docker container
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
      - uses: actions/checkout@master

      - name: Docker login
        run: docker login -u ${GITHUB_ACTOR} -p ${GITHUB_TOKEN} docker.pkg.github.com
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build && push
        run: |
          VERSION=$(node -p "require('./package.json').version")
          docker build -t docker.pkg.github.com/${GITHUB_REPOSITORY}/build:${VERSION} .
          docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/build:${VERSION}
        env:
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}

# TODO: create release draft
# TODO: run docker container in the prod cluster
